sudo: false
language: python
python:
- '2.7'
services:
- postgresql
- elasticsearch
before_script:
- ./setuptests.sh
- sleep 10 # wait for elasticsearch to start
install:
- pip install -r requirements.txt --use-wheel
- pip install coveralls
script:
- ./run-tests.sh
after_success:
- coveralls
before_install:
- openssl aes-256-cbc -K $encrypted_b1ab38410222_key -iv $encrypted_b1ab38410222_iv
  -in id_rsa.travis.enc -out id_rsa.travis -d
- ./scripts/travis.sh
